### ISSUE TITLE
Error - libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by raybg** [An0ther0ne/PyArkan#1]
Getting an error - libpng warning: iCCP: known incorrect sRGB profile

Can anyone help

**Comment by An0ther0ne** [comment]
This is only warning, not error. To eliminate this we can save pictures in
another format. Later maybe I'll do i.

вт, 10 дек. 2019 г. в 05:29, raybg <notifications@github.com>:

**Comment by raybg** [comment]
Hi,

Have converted into .JPG for you and also renamed my code as .jpg. The screen came but nothing is happening in that ???




![desk](https://user-images.githubusercontent.com/31646439/70504702-4fe39200-1b4c-11ea-9a7e-f13a855901ff.jpg)
![ball1](https://user-images.githubusercontent.com/31646439/70504704-4fe39200-1b4c-11ea-944d-e3d101dfe8ec.jpg)
![ball2](https://user-images.githubusercontent.com/31646439/70504706-507c2880-1b4c-11ea-97af-19c07ed127f5.jpg)
![ball3](https://user-images.githubusercontent.com/31646439/70504707-507c2880-1b4c-11ea-9792-267b5a1f3c1b.jpg)
![ball4](https://user-images.githubusercontent.com/31646439/70504709-507c2880-1b4c-11ea-90d5-e2716e6ea86f.jpg)
![ball5](https://user-images.githubusercontent.com/31646439/70504710-5114bf00-1b4c-11ea-80a5-ef6668297601.jpg)
![ball6](https://user-images.githubusercontent.com/31646439/70504711-5114bf00-1b4c-11ea-845a-4f3507d68e63.jpg)
![ball7](https://user-images.githubusercontent.com/31646439/70504712-5114bf00-1b4c-11ea-8f88-412dc8f136c4.jpg)
![brick1](https://user-images.githubusercontent.com/31646439/70504713-51ad5580-1b4c-11ea-97f8-8b92a3ec6a22.jpg)
![brick2](https://user-images.githubusercontent.com/31646439/70504714-51ad5580-1b4c-11ea-9149-5cf2f84192d4.jpg)
![brick3](https://user-images.githubusercontent.com/31646439/70504715-51ad5580-1b4c-11ea-8ca6-20ae6e3a9a86.jpg)
![brick4](https://user-images.githubusercontent.com/31646439/70504717-51ad5580-1b4c-11ea-9c08-d1450a1609ef.jpg)

**Comment by An0ther0ne** [comment]
Just fix this problem now. Download now and fun :)

вт, 10 дек. 2019 г. в 07:26, raybg <notifications@github.com>:

**Comment by An0ther0ne** [comment]
Has been incorrect transparent color in png. I fixed this.

вт, 10 дек. 2019 г. в 08:14, Another One <tn5v2l@gmail.com>:

**Comment by raybg** [comment]
Heyy thanks .. it worked ...  :)
